# Site settings
#baseurl: "/~nashidnoor" # the subpath of your site, e.g. /blog/
#url: https://ece.ubc.ca # the base hostname & protocol for your site

# User settings
title: Parsa Alian
email: palian@ece.ubc.ca
group: SALT lab, UBC
groupweb: http://salt.ece.ubc.ca/
dept: Electrical and Computer Engineering
deptweb: https://www.ece.ubc.ca/
institution: University of British Columbia
institutionweb: https://www.ubc.ca/
address: Vancouver, British Columbia, Canada
github: parsaalian
dblp: 6555.html
gscholar: kfwBRIAAAAJ
linkedin: parsa-alian-394431147

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: Software Engineering, Software Testing, Large Language Models, Deep Learning
copyright: Copyright (c) Parsa Alian

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
